### PR TITLE
Add ReferenceArea component bindings

### PR DESCRIPTION
**Pull request by erykpiast**

### CODE REVIEW

**Comment by liubko** [comment]
@erykpiast thanks!

**Comment by erykpiast** [comment]
You're welcome!

**Comment by erykpiast** [comment]
@liubko what about publishing a new version of the package? at least some pre-release, under `next` tag? do you think you can do that this week? :)

**Comment by liubko** [comment]
> this week

almost... published 0.3.3

===

I have to check notifications settings from Github 😠

**Pull request merged**
